#define VERSION_MAJOR  3
#define VERSION_MINOR  4
#define VERSION_PATCH  0
#define VERSION_EXTRA  ""
#define VERSION_PACKED ((VERSION_MAJOR<<16)|(VERSION_MINOR<<8)|(VERSION_PATCH))
#define VERSION_STRING_NOSP "v3.4.0"
#define VERSION_STRING      " v3.4.0"
